name: Auto Increment Tag
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Obter a última tag
        id: get_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "Última tag: $LAST_TAG"
          echo "last_tag=$LAST_TAG" >> $GITHUB_ENV

      - name: Incrementar a versão
        id: version
        run: |
          LAST_TAG=${{ env.last_tag }}
          # Divide a versão nos pontos (assumindo formato X.Y.Z)
          VERSION_PARTS=(${LAST_TAG//./ })
          PATCH=${VERSION_PARTS[2]}
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"
          echo "Nova tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

      - name: Criar e enviar a nova tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
